### ISSUE TITLE
Unable to sync past block 900013 - version 1.4.0.0

### ISSUE THREAD

**Issue by foomip** [decenomy/SAPP#20]
Once syncing a node from scratch reaches block 900013, it stops syncing and these errors start appearing in the logs.

ERROR: AcceptBlock : prev block f086800cba79e1b725677d40cdce4795578fd0e09ee9f5e49ab8ca3ab287056c is invalid, unable to add block 9297b177a4741dde9266f19877d298f01e3ebe15e39128eb29ae74e27232c3d0
ERROR: ProcessNewBlock : AcceptBlock FAILE

### Machine specs:
- OS: Ubuntu 18.04.4
- CPU: Ryzen 7 3700X
- RAM: 64GB
- Disk size: 1TB
- Disk Type (HD/SDD): HD (Raid 1)

I tried using the bootstrap, but it ends up showing the same error.

**Comment by bedri** [comment]
Fixed with a new bootstrap.

**Comment by foomip** [comment]
Thus is not resolved. After getting to block 901877 all my masternodes and wallet started throwing the same errors.
